### ISSUE TITLE
Invalid Product Collections

### ISSUE THREAD

**Issue by nhughart** [hawksearch/datafeed-magento-2#13]
In \HawkSearch\Datafeed\Observer\Feeds\AbstractProductObserver::getProductCollection, the $store is being used to create the collection, but that collection is then being stored generically in the local $productCollection variable.  If multiple store views are processed in a single run of the datafeed cron, this same collection gets used for all stores to generate the items and attributes.

If necessary I can provide a PR with a fix.

**Comment by martin-cod** [comment]
Was fixed in v2.5.5
